version: '3.8'

services:
  source_db:
    image: postgres:latest
    container_name: source_db
    ports:
      - "5433:5432"
    volumes:
      - source_db_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - etl-net
  
  target_db:
    image: postgres:latest
    container_name: target_db
    ports:
      - "5434:5432"
    volumes:
      - target_db_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - etl-net
  
  api:
    build: ./api
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - source_db
    networks:
      - etl-net
  
  etl:
    build: ./etl
    container_name: etl-container
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - source_db
      - target_db
    networks:
      - etl-net

volumes:
  source_db_data:
  target_db_data:

networks:
  etl-net: